### ISSUE TITLE
Cannot download counter-fitted vectors

### ISSUE THREAD

**Issue by vintersnow** [nesl/nlp_adversarial_examples#1]
Hi!
When I try to run `download_counterfitted_vectors.sh`, it shows a error (403 forbidden) and I cannot download the counter-filterd vectors.
Can you check this out?

**Comment by ylhsieh** [comment]
try this link
https://github.com/nmrksic/counter-fitting/blob/master/word_vectors/counter-fitted-vectors.txt.zip

**Comment by vintersnow** [comment]
Thank you!
